/*
 * This source file was generated by the Gradle 'init' task
 */
package org.batch;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    // @Test public void appHasAGreeting() {
    //     App classUnderTest = new App();
    //     assertNotNull("app should have a greeting", "app should have a greeting");
    // }
}
